### PR TITLE
feat: add token scoping via policies

### PR DESCRIPTION
**Pull request by terrorbyte**
Currently this library does not support handling of token scoping policies as defined in: https://desec.readthedocs.io/en/latest/auth/tokens.html#token-scoping-policies

This PR adds:
- `TokenPolicy` type 
- `GetPolicies(ctx context.Context, tokenID string)` - Get a slice of all the applied policies on a token
  - Associated  basic tests
- `CreatePolicy(ctx context.Context, tokenID string, policy TokenPolicy)` - Apply a policy to the tokens
  - Associated basic tests and an additional test case for a common empty policy creation provided by the docs
- `DeletePolicy(ctx context.Context, tokenID string, policyID string)` - Delete a policy by id
  - Associated basic tests

A few thoughts: 
1. ~If the maintainers think that separating out the policy handling from the token handling I can easily split them up if desired.~
2. ~I need to run the policies on real deSEC with the library before I move this out of draft, at that point I'll also squash the commit for clarity.~

### CODE REVIEW

**Comment by ldez** [comment]
I think you have to remove pointer of string and use `omitempty`

**Comment by terrorbyte** [comment]
Okay. After some struggling through fighting the JSON null marshaling I finally have a working version that can manage policies. 

I'll clean up a few of the tests, squash, add some notes about how to set the `null` value in create policies for the default. Then I'll pull it out of draft.

Here's a quick usage example on one of my testing domains on the real deSEC endpoints:

```go
package main

import (
	"context"
	"fmt"
	"os"

	"github.com/nrdcg/desec"
)

func main() {
	client := desec.New(os.Getenv("DESEC_TOKEN"), desec.ClientOptions{})

	domain := "mil.airforce"
	subname := "desectesting"
	rrtype := "A"

	newRecord, err := client.Records.Create(context.Background(), desec.RRSet{
		Name:    "Policy testing domain",
		Domain:  domain,
		SubName: subname,
		Type:    rrtype,
		TTL:     3600,
		Records: []string{"127.0.0.1"},
	})
	if err != nil {
		fmt.Printf("%#v\n", err.Error())
		os.Exit(1)
	}

	fmt.Printf("Create record: %#v\n", *newRecord)

	newToken, err := client.Tokens.Create(context.Background(), "desec-policy testing")
	if err != nil {
		fmt.Printf("%#v\n", err.Error())
		os.Exit(1)
	}

	fmt.Printf("Create token: %#v\n", (*newToken).ID)
	firstPolicies, err := client.Tokens.GetPolicies(context.Background(), (*newToken).ID)
	if err != nil {
		fmt.Printf("%#v\n", err.Error())
		os.Exit(1)
	}

	fmt.Printf("Token policies: %#v\n", firstPolicies)

	newDefaultPolicy, err := client.Tokens.CreatePolicy(context.Background(), (*newToken).ID, desec.TokenPolicy{Domain: nil, SubName: nil, Type: nil})
	if err != nil {
		fmt.Printf("%#v\n", err.Error())
		os.Exit(1)
	}

	fmt.Printf("Add default policy to token: %#v\n", newDefaultPolicy)
	newRestrictPolicy, err := client.Tokens.CreatePolicy(context.Background(), (*newToken).ID, desec.TokenPolicy{
		Domain:          &domain,
		SubName:         &subname,
		Type:            &rrtype,
		WritePermission: true,
	})

	if err != nil {
		fmt.Printf("%#v\n", err.Error())
		os.Exit(1)
	}

	fmt.Printf("Add restricted policy:  %#v\n", newRestrictPolicy)
	afterPolicies, err := client.Tokens.GetPolicies(context.Background(), (*newToken).ID)

	if err != nil {
		fmt.Printf("%#v\n", err.Error())
		os.Exit(1)
	}

	fmt.Printf("Policies: %#v\n", afterPolicies)

	clientRestricted := desec.New((*newToken).Value, desec.ClientOptions{})
	modRecord, err := clientRestricted.Records.Replace(context.Background(), "mil.airforce", "desectesting", "A", desec.RRSet{
		Name:    "Policy testing domain",
		Domain:  domain,
		SubName: subname,
		Type:    rrtype,
		TTL:     3600,
		Records: []string{"127.0.0.2"},
	})
	if err != nil {
		fmt.Printf("%#v\n", err.Error())
		os.Exit(1)
	}
	fmt.Printf("Modified record with restricted policy: %#v\n", *modRecord)
}

```

And the output:

```console
$ go build && DESEC_TOKEN="$TOKEN" ./desec-policy-testing
Create record: desec.RRSet{Name:"desectesting.mil.airforce.", Domain:"mil.airforce", SubName:"desectesting", Type:"A", Records:[]string{"127.0.0.1"}, TTL:3600, Created:time.Date(2024, time.April, 14, 22, 14, 2, 657420000, time.UTC)}
Create token: "4d84101f-cb61-44f3-86f4-c15c10febbc4"
Token policies: []desec.TokenPolicy{}
Add default policy to token: &desec.TokenPolicy{ID:"b3d047ba-ab75-42b1-ac74-d99e9b63caa1", Domain:(*string)(nil), SubName:(*string)(nil), Type:(*string)(nil), WritePermission:false}
Add restricted policy:  &desec.TokenPolicy{ID:"a58d9a4d-9593-4447-9074-3ac1fb139b92", Domain:(*string)(0xc0004281b0), SubName:(*string)(0xc0004281c0), Type:(*string)(0xc0004281d0), WritePermission:true}
Policies: []desec.TokenPolicy{desec.TokenPolicy{ID:"b3d047ba-ab75-42b1-ac74-d99e9b63caa1", Domain:(*string)(nil), SubName:(*string)(nil), Type:(*string)(nil), WritePermission:false}, desec.TokenPolicy{ID:"a58d9a4d-9593-4447-9074-3ac1fb139b92", Domain:(*string)(0xc000214060), SubName:(*string)(0xc000214070), Type:(*string)(0xc000214080), WritePermission:true}}
Modified record with restricted policy: desec.RRSet{Name:"desectesting.mil.airforce.", Domain:"mil.airforce", SubName:"desectesting", Type:"A", Records:[]string{"127.0.0.2"}, TTL:3600, Created:time.Date(2024, time.April, 14, 22, 14, 2, 657420000, time.UTC)}
```

**Comment by ldez** [comment]
can you provide more information about the `null`?

**Comment by terrorbyte** [comment]
Absolutely, so this appears to be the only endpoint that can have mixed empty values and JSON null values (see the "Field Reference" for why that is and priority: https://desec.readthedocs.io/en/latest/auth/tokens.html#token-policy-field-reference). Because of that we need to be able to have a way to set empty strings and JSON nulls.

In order to set a policy with a null value, such as the default policy to enable the policy default-deny, you can use a `nil` to marshal it to the `null` type, ie: 
```go
client.Tokens.CreatePolicy(context.Background(), (*newToken).ID, desec.TokenPolicy{Domain: nil, SubName: nil, Type: nil})
```

The way I got this to work was to set the `TokenPolicy` struct to utilize `*string` and then to remove the `omitempty` to force the `null` value into the struct vs removing it. Unfortunately, that does also mean that you can't set hardcoded strings and have to pass them by pointer but I don't see a easy way around that unless you want to add one of the nullable package dependencies.

I was getting it mixed up in my own head in the last couple of pushes because I was juggling `omitempty`, `nil`, and reference to empty string that I falsely thought might marshal to `null` while keeping `omitempty`.

**Comment by ldez** [comment]
FYI, you don't need to do that `(*newToken).ID`, you can call `ID` on the pointer of Token `newToken.ID`.
Same thing for `(*newToken).Value` (-> `newToken.Value`).

**Comment by ldez** [comment]
Is your PR ready for review?

**Comment by ldez** [comment]
FYI you don't need to squash your commits, I will squash them during the merge.

**Comment by ldez** [comment]
> If the maintainers think that separating out the policy handling from the token handling I can easily split them up if desired.

Can you create a file named `token_policies.go` with a `TokenPoliciesService`?

**Review by ldez — APPROVED** [review]

**Pull request merged**
